language: ruby
sudo: false
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5.0
before_install:
  - gem update --system # fix ruby 2.5 travis build issue
gemfile:
  - gemfiles/mail_2.6.gemfile
  - gemfiles/mail_2.7.gemfile
script:
  - bundle exec rake
notifications:
  email:
    on_success: change
    on_failure: always
